/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appScenariosIndexRouteImport } from './routes/(app)/scenarios/index'
import { Route as appProfilesIndexRouteImport } from './routes/(app)/profiles/index'
import { Route as appCameraSettingsIndexRouteImport } from './routes/(app)/camera-settings/index'
import { Route as appArtifactsIndexRouteImport } from './routes/(app)/artifacts/index'
import { Route as appScenariosCreateRouteImport } from './routes/(app)/scenarios/create'
import { Route as appScenariosScenarioIdRouteImport } from './routes/(app)/scenarios/$scenario-id'
import { Route as appArtifactsArtifactIdIndexRouteImport } from './routes/(app)/artifacts/$artifact-id/index'
import { Route as appAcquisitionsAcquisitionIdIndexRouteImport } from './routes/(app)/acquisitions/$acquisition-id/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appScenariosIndexRoute = appScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfilesIndexRoute = appProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCameraSettingsIndexRoute = appCameraSettingsIndexRouteImport.update({
  id: '/camera-settings/',
  path: '/camera-settings/',
  getParentRoute: () => appRouteRoute,
} as any)
const appArtifactsIndexRoute = appArtifactsIndexRouteImport.update({
  id: '/artifacts/',
  path: '/artifacts/',
  getParentRoute: () => appRouteRoute,
} as any)
const appScenariosCreateRoute = appScenariosCreateRouteImport.update({
  id: '/scenarios/create',
  path: '/scenarios/create',
  getParentRoute: () => appRouteRoute,
} as any)
const appScenariosScenarioIdRoute = appScenariosScenarioIdRouteImport.update({
  id: '/scenarios/$scenario-id',
  path: '/scenarios/$scenario-id',
  getParentRoute: () => appRouteRoute,
} as any)
const appArtifactsArtifactIdIndexRoute =
  appArtifactsArtifactIdIndexRouteImport.update({
    id: '/artifacts/$artifact-id/',
    path: '/artifacts/$artifact-id/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAcquisitionsAcquisitionIdIndexRoute =
  appAcquisitionsAcquisitionIdIndexRouteImport.update({
    id: '/acquisitions/$acquisition-id/',
    path: '/acquisitions/$acquisition-id/',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scenarios/$scenario-id': typeof appScenariosScenarioIdRoute
  '/scenarios/create': typeof appScenariosCreateRoute
  '/artifacts/': typeof appArtifactsIndexRoute
  '/camera-settings/': typeof appCameraSettingsIndexRoute
  '/profiles/': typeof appProfilesIndexRoute
  '/scenarios/': typeof appScenariosIndexRoute
  '/acquisitions/$acquisition-id/': typeof appAcquisitionsAcquisitionIdIndexRoute
  '/artifacts/$artifact-id/': typeof appArtifactsArtifactIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scenarios/$scenario-id': typeof appScenariosScenarioIdRoute
  '/scenarios/create': typeof appScenariosCreateRoute
  '/artifacts': typeof appArtifactsIndexRoute
  '/camera-settings': typeof appCameraSettingsIndexRoute
  '/profiles': typeof appProfilesIndexRoute
  '/scenarios': typeof appScenariosIndexRoute
  '/acquisitions/$acquisition-id': typeof appAcquisitionsAcquisitionIdIndexRoute
  '/artifacts/$artifact-id': typeof appArtifactsArtifactIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/scenarios/$scenario-id': typeof appScenariosScenarioIdRoute
  '/(app)/scenarios/create': typeof appScenariosCreateRoute
  '/(app)/artifacts/': typeof appArtifactsIndexRoute
  '/(app)/camera-settings/': typeof appCameraSettingsIndexRoute
  '/(app)/profiles/': typeof appProfilesIndexRoute
  '/(app)/scenarios/': typeof appScenariosIndexRoute
  '/(app)/acquisitions/$acquisition-id/': typeof appAcquisitionsAcquisitionIdIndexRoute
  '/(app)/artifacts/$artifact-id/': typeof appArtifactsArtifactIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scenarios/$scenario-id'
    | '/scenarios/create'
    | '/artifacts/'
    | '/camera-settings/'
    | '/profiles/'
    | '/scenarios/'
    | '/acquisitions/$acquisition-id/'
    | '/artifacts/$artifact-id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scenarios/$scenario-id'
    | '/scenarios/create'
    | '/artifacts'
    | '/camera-settings'
    | '/profiles'
    | '/scenarios'
    | '/acquisitions/$acquisition-id'
    | '/artifacts/$artifact-id'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/scenarios/$scenario-id'
    | '/(app)/scenarios/create'
    | '/(app)/artifacts/'
    | '/(app)/camera-settings/'
    | '/(app)/profiles/'
    | '/(app)/scenarios/'
    | '/(app)/acquisitions/$acquisition-id/'
    | '/(app)/artifacts/$artifact-id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/scenarios/': {
      id: '/(app)/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof appScenariosIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profiles/': {
      id: '/(app)/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof appProfilesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/camera-settings/': {
      id: '/(app)/camera-settings/'
      path: '/camera-settings'
      fullPath: '/camera-settings/'
      preLoaderRoute: typeof appCameraSettingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/artifacts/': {
      id: '/(app)/artifacts/'
      path: '/artifacts'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof appArtifactsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/scenarios/create': {
      id: '/(app)/scenarios/create'
      path: '/scenarios/create'
      fullPath: '/scenarios/create'
      preLoaderRoute: typeof appScenariosCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/scenarios/$scenario-id': {
      id: '/(app)/scenarios/$scenario-id'
      path: '/scenarios/$scenario-id'
      fullPath: '/scenarios/$scenario-id'
      preLoaderRoute: typeof appScenariosScenarioIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/artifacts/$artifact-id/': {
      id: '/(app)/artifacts/$artifact-id/'
      path: '/artifacts/$artifact-id'
      fullPath: '/artifacts/$artifact-id/'
      preLoaderRoute: typeof appArtifactsArtifactIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/acquisitions/$acquisition-id/': {
      id: '/(app)/acquisitions/$acquisition-id/'
      path: '/acquisitions/$acquisition-id'
      fullPath: '/acquisitions/$acquisition-id/'
      preLoaderRoute: typeof appAcquisitionsAcquisitionIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appScenariosScenarioIdRoute: typeof appScenariosScenarioIdRoute
  appScenariosCreateRoute: typeof appScenariosCreateRoute
  appArtifactsIndexRoute: typeof appArtifactsIndexRoute
  appCameraSettingsIndexRoute: typeof appCameraSettingsIndexRoute
  appProfilesIndexRoute: typeof appProfilesIndexRoute
  appScenariosIndexRoute: typeof appScenariosIndexRoute
  appAcquisitionsAcquisitionIdIndexRoute: typeof appAcquisitionsAcquisitionIdIndexRoute
  appArtifactsArtifactIdIndexRoute: typeof appArtifactsArtifactIdIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appScenariosScenarioIdRoute: appScenariosScenarioIdRoute,
  appScenariosCreateRoute: appScenariosCreateRoute,
  appArtifactsIndexRoute: appArtifactsIndexRoute,
  appCameraSettingsIndexRoute: appCameraSettingsIndexRoute,
  appProfilesIndexRoute: appProfilesIndexRoute,
  appScenariosIndexRoute: appScenariosIndexRoute,
  appAcquisitionsAcquisitionIdIndexRoute:
    appAcquisitionsAcquisitionIdIndexRoute,
  appArtifactsArtifactIdIndexRoute: appArtifactsArtifactIdIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
